// Writes web/public/index.html — a plain listing of the files in web/public,
// because Netlify serves files but never lists a folder.
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const dir = join(dirname(fileURLToPath(import.meta.url)), "..", "web", "public");
const skip = new Set(["index.html", "README.md"]);
const human = (n) => n < 1024 ? `${n} B` : n < 1048576 ? `${(n / 1024).toFixed(1)} KB` : `${(n / 1048576).toFixed(1)} MB`;
const files = readdirSync(dir).filter(f => !skip.has(f) && !f.startsWith(".")).sort()
  .map(f => ({ name: f, size: statSync(join(dir, f)).size, mtime: statSync(join(dir, f)).mtime }));
const esc = (s) => s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const rows = files.map(f => `<li><a href="${encodeURIComponent(f.name)}">${esc(f.name)}</a> <span>${human(f.size)} · ${f.mtime.toISOString().slice(0, 10)}</span></li>`).join("\n");
writeFileSync(join(dir, "index.html"), `<!doctype html>
<meta charset="utf-8">
<title>Motionstill Cut — public files</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  body{font:15px/1.5 system-ui,sans-serif;max-width:46rem;margin:3rem auto;padding:0 1rem;color:#222;background:#fafafa}
  h1{font-size:1.25rem}ul{list-style:none;padding:0}li{padding:.4rem 0;border-bottom:1px solid #e5e5e5;display:flex;justify-content:space-between;gap:1rem}
  a{color:#1a5fb4;text-decoration:none;word-break:break-all}a:hover{text-decoration:underline}span{color:#777;white-space:nowrap;font-size:.85em}
  @media(prefers-color-scheme:dark){body{background:#151719;color:#ddd}li{border-color:#2a2d31}a{color:#7fb2e5}span{color:#999}}
</style>
<h1>Motionstill Cut — public files</h1>
<ul>
${rows || "<li>Nothing here yet.</li>"}
</ul>
<p><small>${files.length} file${files.length === 1 ? "" : "s"}. Committed to <code>web/public/</code> in the repo; this list is generated by <code>npm run public:index</code>.</small></p>
`);
console.log(`web/public/index.html — ${files.length} file(s)`);
